#settings for SleepingServerStarter

serverName: SleepingServer, waiting for his prince...
serverPort: 25565
loginMessage: ...Waking server up, come back in a minute...
serverOnlineMode: true
serverVersion: "1.9.4"

webPort: 0	 					# 0 to disable web hosting, 8123default dynmap
webDir: plugins/dynmap/web 	# dir of dynmap web

startMinecraft: 1 				# 0 to disable	
minecraftCommand: java -Xmx1024M -Xms1024M -XX:MaxPermSize=128M -jar spigot.jar nogui
