# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Commit Build

on:
  push:
    branches: [ master, feature/* , chore/* ]
  pull_request:
    branches: [ master, feature/* , chore/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - name: 'Upload Artifact Windows'
      uses: actions/upload-artifact@v2
      with:
        name: 'Binary Windows'
        path: bin/mcsleepingserverstarter-win-x64.exe
    - name: 'Upload Artifact Linux'
      uses: actions/upload-artifact@v2
      with:
        name: 'Binary Linux'
        path: bin/mcsleepingserverstarter-linux-x64
    - name: 'Upload Artifact Linux arm64'
      uses: actions/upload-artifact@v2
      with:
        name: 'Binary Linux arm64 (Raspberry Pi)'
        path: bin/mcsleepingserverstarter-linux-arm64       
